package jflex;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int NEQUIV = 20;
  public static final int ELSE = 5;
  public static final int PLUS = 10;
  public static final int RPAREN = 24;
  public static final int SEMI = 21;
  public static final int WHILE = 6;
  public static final int RCURLY = 28;
  public static final int EQUALEQUAL = 19;
  public static final int RETURN = 9;
  public static final int GREATER = 16;
  public static final int IF = 4;
  public static final int LPAREN = 23;
  public static final int ID = 2;
  public static final int NUM = 3;
  public static final int LCURLY = 27;
  public static final int COMMA = 22;
  public static final int EOF = 0;
  public static final int DIV = 13;
  public static final int LSQUARE = 25;
  public static final int MINUS = 11;
  public static final int error = 1;
  public static final int GEQUIV = 18;
  public static final int EQ = 14;
  public static final int RSQUARE = 26;
  public static final int LEQUIV = 17;
  public static final int INTEGER = 7;
  public static final int MUL = 12;
  public static final int VOID = 8;
  public static final int LESS = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "NUM",
  "IF",
  "ELSE",
  "WHILE",
  "INTEGER",
  "VOID",
  "RETURN",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "EQ",
  "LESS",
  "GREATER",
  "LEQUIV",
  "GEQUIV",
  "EQUALEQUAL",
  "NEQUIV",
  "SEMI",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LSQUARE",
  "RSQUARE",
  "LCURLY",
  "RCURLY"
  };
}

